# -*- mode: org; mode: auto-fill; fill-column: 75; -*- 
#+TITLE: Community Assoc Ballot Tallying Aid
#+AUTHOR: Enoch
#+EMAIL: ixew@hotmail.com
#+OPTIONS: email:t
#+STARTUP: indent

* General

~vote~ is a quick ballot tallying program that was written for some
troubled high rise community in the North East of the USA.  This community
votes through weighted shares. Data entry is optimized for the use of blind
right-hand PC numeric-pad typing.  ~vote~ uses the SQLite database library
(sqlite3 version) and is written in C. To examine the database file
collected ballots use [[http://sqlitebrowser.org/][SQLITEbrowser]] or a similar tool.

~vote.exe~, the equivalent Microsoft Windows version, is built on Linux
using [[https://mxe.cc/][MXE (M cross environment)]]. Here is the latest [[./Windows-binary-release.zip][Windows binary release]].

* Software License and Legal Disclaimer

The software in this repository is in the public domain following the model
set by the [[http://www.sqlite.org/copyright.html][SQLite Project]]. The software is offered “as-is”, without
warranty, and disclaiming liability for damages resulting from its use.

* Prerequisite

If not provided, create the SQLite data base file ~condo.db~ (this filename
is set in the Makefile) with the following table of shares:

#+begin_example
CREATE TABLE shares (
	apt	INTEGER PRIMAY KEY,
	share	INTEGER,
	code	BLOB
);
#+end_example

Fill the ~shares~ table with your community ~apt~ (apartment number) and
~share~ value pairs (ignore the ~code~ column).

* Program initialization

Run ~vote -i <seats>:<candidates>[:+]~ [fn:1] to initialize the ~condo.db~
database file. If the optional ~:+~ argument is added, the security ~code~
in ~shares~ would be initialized with random two-byte BLOBs. These security
codes can be used on printed forms that are mailed to the shareholders to
enhance the security of the election. They can substitute the need for
using an expensive special paper to prevent [[https://ballotpedia.org/Ballot_stuffing][Ballot Stuffing]]. You can export
the (apt, code) pairs to a ~secure.csv~ spreadsheet as follows:

#+begin_example
$ sqlite3 condo.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> .output secure.csv
sqlite> .headers on
sqlite> .mode csv
sqlite> select apt, hex(code) as code from shares order by apt;
sqlite> .quit
#+end_example

An empty table of ~votes~ would be created or *recreated if it already
exists*. The ~votes~ table has the following structure:

#+begin_example
CREATE TABLE votes (
      apt INTEGER PRIMAY KEY,
      vtime INTEGER,
      can1 INTEGER DEFAULT 0,
      ...
);
#+end_example

vtime is the "unix time" of enering the apt vote; It is captured for
forensic purposes only.

* Examples

Initialize with new security codes:

#+begin_example
Microsoft Windows [Version 10.0.19043.1237]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ixew>cd Desktop

C:\Users\ixew\Desktop>vote -i 2:4:+
condo.db loader. Exit by Ctrl-Z (EOF). EW Oct 11 2021.
condo: apts=614 shares=1000005
Enter negative apt to delete an apt vote.
Seats = 2, Candidates = 4

Voted: apts=0 shares=N/A c1=N/A c2=N/A c3=N/A
Apt.Can1.Can2... ^Z
EOF
condo.db changed.
Press Enter to end...

C:\Users\ixew\Desktop>
#+end_example

Use:

#+begin_example
condo.db loader. Exit by Ctrl-Z (EOF). EW Oct 11 2021.
Enter negative apt to delete an apt vote.
Seats = 2, Candidates = 4

Voted: apts=0 shares=N/A c1=N/A c2=N/A c3=N/A
Apt.Can1.Can2... 3121.1.2
Ballot: share=1371 code=0xDD17

Voted: apts=1 shares=1371 c1=1371 c2=1371 c3=0
Apt.Can1.Can2... 3120.3.4
Ballot: share=2150 code=0xFA9E

Voted: apts=2 shares=3521 c3=2150 c4=2150 c1=1371
Apt.Can1.Can2... 2
APT UNKNOWN

Voted: apts=2 shares=3521 c3=2150 c4=2150 c1=1371
Apt.Can1.Can2... 7.5.6
Ballot: share=1340 code=0xED04
ILL CAN

Voted: apts=2 shares=3521 c3=2150 c4=2150 c1=1371
Apt.Can1.Can2... 7
Ballot: share=1340 code=0xED04

Voted: apts=3 shares=4861 c3=2150 c4=2150 c1=1371
Apt.Can1.Can2... -7
DELETED APT NO 7

Voted: apts=2 shares=3521 c3=2150 c4=2150 c1=1371
Apt.Can1.Can2... ^Z
EOF
condo.db changed.
Press Enter to end...
#+end_example

* Footnotes

[fn:1] To open a Windows Terminal type ~WIN+R~ and then the ~cmd~ command.
