# -*- mode: org; mode: auto-fill; fill-column: 75; -*- 
#+TITLE: Community Assoc Ballot Tallying Aid
#+AUTHOR: Enoch
#+EMAIL: ixew@hotmail.com
#+OPTIONS: email:t
#+STARTUP: indent

* General

~vote~ is a quick ballot tallying program that was originally written in
2014 for some troubled high rise community in the North East of the USA.
This community votes through weighted shares. Data entry is optimized for
the use of blind right-hand PC numeric-pad typing.  ~vote~ uses the SQLite
database library (sqlite3 version) and is written in C. To examine the
database file collected ballots use [[http://sqlitebrowser.org/][SQLITEbrowser]] or a similar tool.

~vote.exe~, the equivalent Microsoft Windows version, is built on Linux
using [[https://mxe.cc/][MXE (M cross environment)]]. Here is the latest [[./Windows-binary-release.zip][Windows binary release]].

* Software License and Legal Disclaimer

The software in this repository is in the public domain following the model
set by the [[http://www.sqlite.org/copyright.html][SQLite Project]]. The software is offered “as-is”, without
warranty, and disclaiming liability for damages resulting from its use.

* Prerequisite

If not provided, create the SQLite data base file ~condo.db~ (this filename
is set in the Makefile) with the following table of shares:

#+begin_example
CREATE TABLE "shares" (
	"apt"	INTEGER,
	"share"	INTEGER,
	"code"	INTEGER UNIQUE,
	PRIMARY KEY("apt")
);
#+end_example

Fill the ~shares~ table with your community ~apt~ (apartment number) /
~share~ value pairs. Ignore the ~code~ colum, it would hold random numbers
necessary for the anonymous tallying method.

* Program initialization

Run ~vote -i <seats>:<candidates>[:x]~ to initialize the program's
~condo.db~ SQLite database file; this requires opening a terminal[fn:1].

The optional third argument, ~:x~ or ~:X~, initializes the program for the
use of secret (anonymous) apartment numbers rather than real numbers during
sensitive (publicly observed) tallying. *NOTE!* Only when using the upper
case ~:X~ argument would new secret apartment numbers be
generated. Lower-case ~:x~ argument initializes the program to use the
pre-existing secret numbers. This is convenient when needing to switch
between *secret* and *real* apartment numbers tally.

An "anon" table is created to relate the real apartment number with its
secret counterpart. 

A "bans" table of *real* apartment numbers can be provided to reject votes
from those apartments.

An empty table of ~votes~ would be created or *recreated if it already
exists*. The ~votes~ table has the following structure:

#+begin_example
CREATE TABLE votes (
      apt INTEGER PRIMAY KEY,
      vtime INTEGER,
      can1 INTEGER DEFAULT 0,
      ...
);
#+end_example

vtime is the "unix time" of entering the apt vote; It is captured for
forensic purposes only.

* Footnotes

[fn:1] To open a Windows Terminal type ~WIN+R~ and then the ~cmd~ command.
