# -*- mode: org; mode: auto-fill; fill-column: 75; -*- 
#+TITLE: Condo Assoc Ballot Tallying Aid
#+AUTHOR: Enoch
#+EMAIL: ixew@hotmail.com
#+OPTIONS: email:t
#+STARTUP: indent

* Election SQLite Loader
** General

The following is a "quick & dirty" ballot tallying program for the benefit
of some troubled high rise community in the North East of the USA. Data
entry is optimized for the use of "blind" right-hand PC numeric-pad typing.
This program uses the SQLite data base and is written in C. To examine
collected votes use a program like [[http://sqlitebrowser.org/][SQLITEbrowser]] on the database file.

This community votes through weighted shares.

** Software License

The software in this repository is in the public domain, following the
example set by the [[http://www.sqlite.org/copyright.html][SQLite Project]].

** sqlite3.exe mycondo.db

Create a database with a table of shares:
#+begin_example
CREATE TABLE "shares" (
	`apt`	INTEGER,
	`share`	INTEGER,
	`code`	BLOB,
	PRIMARY KEY(apt)
)
#+end_example

** vote [-i <seats>:<candidates>]

Initialize the "mycondo.db" database file; This includes changing the
security code (two byte BLOB field) in the table of shares.
